### PR TITLE
Integrate Omnigrasper

### PR DESCRIPTION
**Pull request by dogoepp**
If you love the new arm, you'll fall for this model. Please accept ;-)

### CODE REVIEW

**Comment by costashatz** [comment]
@dogoepp for some reason (I haven't it investigated too much), DART cannot load the STL files you provided. I will make an issue in dart, but meanwhile (so that we can work with the repo) I will make them collada (.dae). Is it ok for you?

**Comment by costashatz** [comment]
@dogoepp investigating a bit more. DART uses assimp to load the files and when loading our files we get the following error: **STL: ASCII file is empty or invalid; no data loaded**. Opening the files with Blender and re-saving in STL works but loads the models without texture:

arm_screen

Loading the same exact models in ROS/rviz has no problem...

arm_screen2

Exploring more in DART, I found a hacky way to make it show colors. They are not ideal, but I will send an issue to them to investigate it more...

arm_screen3

Meanwhile, I am going to change the STLs to the ones I exported from Blender that seems to work better with DART.

**Comment by dogoepp** [comment]
From the Dart error, I assume that it expects the ASCII version of STL while the ones I made with SolidWorks are in binary form. I can convert them directly (with a dedicated tool) or you can use Blender, as you like, but It would be nice to keep the original files in the repo, as a reference.

Besides, How would you convert STL to DAE ? I'm intereseted.

**Comment by costashatz** [comment]
> I can convert them directly (with a dedicated tool) or you can use Blender, as you like, but It would be nice to keep the original files in the repo, as a reference.

I already converted them using Blender (and pushed the changes). But feel free to put the original ones in the repo for reference..

> From the Dart error, I assume that it expects the ASCII version of STL while the ones I made with SolidWorks are in binary form.

No. It can load binary (at least *assimp* says it can), but solidworks puts a weird header that confuses the loader of *assimp* (check [here](http://stackoverflow.com/questions/20007058/loading-binary-stl-model-with-assimp) --- although they say that in the newer versions they fixed it).

> Besides, How would you convert STL to DAE ? I'm intereseted.

Blender is your friend... ;) But I am using STL for now, since it works..

**Comment by costashatz** [comment]
After my experiments with DART, we should put the proper damping/friction coefficients for the joints. I will do it this week..

**Comment by dogoepp** [comment]
Was it done in the time or is the addition of damping and friction coefficients still a todo ?

In the latter case, we could maybe still merge this and do the addition later, shouldn't we ?

**Comment by dogoepp** [comment]
@costashatz I modified for the new configuration layout. Can we merge ?

**Comment by costashatz** [comment]
**Seems ok for me to merge**

**Comment by dogoepp** [comment]
**Merging**

**Pull request merged**
